vim.keymap.set('n', '-', '<cmd>Ex<cr>')
vim.keymap.set('n', '<C-u>', '<C-u>zz', { desc = 'Up page and center it', silent = true })
vim.keymap.set('n', '<C-d>', '<C-d>zz', { desc = 'Down page and center it', silent = true })
vim.keymap.set('n', 'n', 'nzzzv', { desc = 'center next ocurrecie' })
vim.keymap.set('n', 'N', 'Nzzzv', { desc = 'center previous ocurrecie' })
vim.keymap.set('v', '<', '<gv', { desc = 'Tab with selection' })
vim.keymap.set('v', '>', '>gv', { desc = 'Tab with selection' })
vim.keymap.set('n', '*', '*zzzv', { desc = '' })
vim.keymap.set('n', '#', '#zzzv', { desc = '' })
vim.keymap.set('v', 'J', ":m '>+1<cr>gv=gv")
vim.keymap.set('v', 'K', ":m '<-2<cr>gv=gv")
vim.keymap.set('n', '<leader>y', '"+y')
vim.keymap.set('n', '<leader>Y', '"+Y')
vim.keymap.set('v', '<leader>y', '"+y')
vim.keymap.set('n', '<leader>p', '"+p')
vim.keymap.set('n', '<leader>P', '"+P')
vim.keymap.set('v', '<leader>p', '"+p')
vim.keymap.set('n', '<leader><C-T>', '<esc><C-W>v<C-W><C-W><cmd>terminal<cr>A', { desc = 'Create a split window and open the terminal' })
vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('i', '<C-S>', '<esc>A;<esc>')
vim.keymap.set('n', '<cr>', '<esc>A<cr>')
vim.keymap.set('n', '<C-]>', ':cnext<cr>')
vim.keymap.set('n', '<C-[>', ':cprev<cr>')
vim.keymap.set('n', '<leader>P', '"+p', { desc = 'Paste from clipboard' })
